IGI/LR5/zoo_shop/zoo_shop/urls.py
"""
URL configuration for zoo_shop project.

The `urlpatterns` list routes URLs to views_app. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views_app
    1. Add an import:  from my_app import views_app
    2. Add a URL to urlpatterns:  path('', views_app.home, name='home')
Class-based views_app
    1. Add an import:  from other_app.views_app import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("zoo_shop_app.urls")),
]

IGI/LR5/zoo_shop/zoo_shop_app/urls.py
from django.urls import path

from zoo_shop_app.views_app.home_view import home
from zoo_shop_app.views_app.about_view import about
from zoo_shop_app.views_app.contacts_view import contacts
from zoo_shop_app.views_app.promocodes_view import *
from zoo_shop_app.views_app.privacy_policy_view import privacy_policy
from zoo_shop_app.views_app.suppliers_view import suppliers
from zoo_shop_app.views_app.account_view import register, login, logout
from zoo_shop_app.views_app.api_views import facts_about_cats, images_dogs
from zoo_shop_app.views_app.news_view import news, article_detail
from zoo_shop_app.views_app.products_view import *
from zoo_shop_app.views_app.review_view import reviews, add_review
from zoo_shop_app.views_app.vacancies_view import *
from zoo_shop_app.views_app.shopping_cart import *
from zoo_shop_app.views_app.sales_view import *
from zoo_shop_app.views_app.faq_view import *
from zoo_shop_app.views_app.orders_view import orders
from zoo_shop_app.views_app.static_view import sales_chart
from django.urls import re_path
from zoo_shop_app.views_app.download_certificate import download_certificate


urlpatterns = [
    re_path(r'^$', home, name='home'),
    re_path(r'^home/$', home, name='home'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^contacts/$', contacts, name='contacts'),
    re_path(r'^news/$', news, name='news'),
    path('article_detail/<int:id>/', article_detail, name='article_detail'),
    re_path(r'^faq/$', faq, name='faq'),
    re_path(r'^contacts/$', contacts, name='contacts'),
    re_path(r'^privacy_policy/$', privacy_policy, name='privacy_policy'),
    re_path(r'^reviews/$', reviews, name='reviews'),
    re_path(r'^add_review/$', add_review, name='add_review'),

    re_path(r'^products/$', products, name='products'),
    path('product/<int:product_id>/', product_detail, name='product_detail'),

    re_path(r'^promocodes/$', promocodes, name='promocodes'),
    re_path(r'^register/$', register, name='register'),
    re_path(r'^login/$', login, name='login'),
    re_path(r'^suppliers/$', suppliers, name='suppliers'),
    re_path(r'^logout/$', logout, name='logout'),
    re_path(r'^cats_facts/$', facts_about_cats, name='cats_facts'),
    re_path(r'^dogs_images/$', images_dogs, name='dogs_images'),

    path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    re_path(r'^cart/$', cart_management, name='cart_management'),
    re_path(r'^clear-cart/$', clear_cart, name='clear_cart'),
    path('remove_from_cart/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    re_path(r'^order/create/$', create_order, name='create_order'),
    path('order/confirmation/<int:order_id>/', order_confirmation, name='order_confirmation'),
    path('update_cart/<int:item_id>/', update_cart, name='update_cart'),

    re_path(r'^orders/$', orders, name='orders'),
    re_path(r'^sales_chart/$', sales_chart, name='sales_chart'),

    re_path(r'^faq_list/$', FAQListView.as_view(), name='faq_list'),
    path('faq/<int:pk>/', FAQDetailView.as_view(), name='faq_detail'),
    re_path(r'^faq/create/$', FAQCreateView.as_view(), name='faq_create'),
    path('faq/<int:pk>/update/', FAQUpdateView.as_view(), name='faq_update'),
    path('faq/<int:pk>/delete/', FAQDeleteView.as_view(), name='faq_delete'),


    re_path(r'^vacancy_list/$', vacancy_list, name='vacancy_list'),
    re_path(r'^vacancies/create/$', vacancy_create, name='vacancy_create'),
    path('vacancies/<int:vacancy_id>/', vacancy_detail, name='vacancy_detail'),
    path('vacancies/<int:vacancy_id>/update/', vacancy_update, name='vacancy_update'),
    path('vacancies/<int:vacancy_id>/delete/', vacancy_delete, name='vacancy_delete'),


    re_path(r'^promocode_list/$', promocode_list, name='promocode_list'),
    re_path(r'^promocodes/create/$', promocode_create, name='promocode_create'),
    path('promocodes/<int:promocode_id>/', promocode_detail, name='promocode_detail'),
    path('promocodes/<int:promocode_id>/update/', promocode_update, name='promocode_update'),
    path('promocodes/<int:promocode_id>/delete/', promocode_delete, name='promocode_delete'),


    re_path(r'^download_certificate/$', download_certificate, name='download_certificate'),

]

IGI/LR5/zoo_shop/zoo_shop_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime
import random


class Base(models.Model):
    id = models.BigAutoField(primary_key=True)
    created = models.DateTimeField(default=timezone.now)
    update = lastUpdate = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True


class AboutShop(Base):
    text = models.TextField('Shop description')
    image = models.ImageField(upload_to='static/main/')

    def __str__(self):
        return f'{self.id}'

    class Meta:
        db_table = 'about_shop'


class Category(Base):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        db_table = 'categories'
        ordering = ['name']


class Client(Base):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=30, unique=True)
    birth_date = models.DateField(
        validators=[MaxValueValidator(datetime.date.today() - datetime.timedelta(days=18 * 365),
                                      message="You must be at least 18 years old to register")], null=True)
    photo = models.ImageField(upload_to='static/clients/', default='static/main/user.png')
    email = models.EmailField(max_length=50, unique=True)
    phone = models.CharField(max_length=13, unique=True)
    password = models.CharField(max_length=50, default="")

    def __str__(self):
        return f'{self.name} {self.email} {self.phone}'

    class Meta:
        ordering = ['name']
        db_table = 'clients'


class Employee(Base):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=30, unique=True)
    birth_date = models.DateField(
        validators=[MaxValueValidator(datetime.date.today() - datetime.timedelta(days=18 * 365),
                                      message="You must be at least 18 years old to register")], null=True)
    email = models.EmailField(max_length=50, unique=True)
    phone = models.CharField(max_length=13, unique=True)
    position = models.CharField(max_length=50)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.ImageField(upload_to='static/employees/', default='static/main/user.png')
    password = models.CharField(max_length=50, default="")

    def __str__(self):
        return (f'{self.id} {self.name} {self.email} {self.phone} '
                f'{self.position} {self.salary}')

    class Meta:
        ordering = ['name']
        db_table = 'employees'


class Supplier(Base):
    name = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    phone = models.CharField(max_length=13, unique=True)
    email = models.EmailField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name} {self.country} {self.phone} {self.email}'

    class Meta:
        db_table = 'suppliers'
        ordering = ['name']


class Product(Base):
    article = models.CharField(max_length=255)
    name = models.CharField(max_length=100)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='static/products/', default='static/main/empty.jpg')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.article} {self.name} {self.supplier} {self.price} {self.category}'

    class Meta:
        db_table = 'products'

    def save(self, *args, **kwargs):
        if not self.article:
            existing_product = Product.objects.filter(name=self.name).first()
            if existing_product:
                self.article = existing_product.article
            else:
                self.article = self.generate_unique_article()
        super(Product, self).save(*args, **kwargs)

    def generate_unique_article(self):
        while True:
            article = ''.join(random.choices('0123456789', k=6))
            if not Product.objects.filter(article=article).exists():
                return article


class FAQ(Base):
    question = models.CharField(max_length=100, default='')
    answer = models.TextField(max_length=500, default='')

    def __str__(self):
        return f'{self.id} {self.question} {self.answer}'

    class Meta:
        ordering = ['created']
        db_table = 'questions'


class News(Base):
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='static/news/', default='static/main/news.png')

    def __str__(self):
        return f'{self.id} {self.title} {self.text} {self.image}'

    class Meta:
        db_table = 'news'
        ordering = ['created']


class Promocode(Base):
    discount = models.IntegerField(default=0, help_text='Discount',
                                   validators=[MinValueValidator(1), MaxValueValidator(100)])
    archived = models.BooleanField()
    code = models.CharField(max_length=10, default='zoobazar', help_text='Promocode')
    text = models.CharField(max_length=100)
    valid_date = models.DateField()

    def __str__(self):
        return f'{self.id} {self.text} {self.discount}'

    class Meta:
        db_table = 'promocodes'

    def is_valid(self):
        return not self.archived and self.valid_date >= timezone.now().date()

    def apply_discount(self, original_price):
        if self.is_valid():
            discount_amount = original_price * (self.discount / 100)
            return max(original_price - discount_amount, 0)
        return original_price


class RegularClient(Base):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id} {self.client}'

    class Meta:
        db_table = 'regular_clients'


class Review(Base):
    author = models.ForeignKey(Client, on_delete=models.CASCADE)
    text = models.TextField()
    rate = models.IntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])

    def __str__(self):
        return f'{self.id} {self.author} {self.rate} {self.created}'

    class Meta:
        ordering = ['id']
        db_table = 'reviews'


class Sales(Base):
    products = models.ManyToManyField(Product)
    total_cost = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    address = models.CharField(default='Minsk, Gikalo 9', max_length=100)

    class Meta:
        ordering = ['created']
        db_table = 'sales'


class ShoppingCart(Base):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.id} {self.client} {self.product}'

    class Meta:
        ordering = ['id']
        db_table = 'shopping_carts'


class Vacancy(Base):
    position = models.CharField(max_length=100)
    description = models.TextField()
    salary = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.id} {self.salary} {self.position}'

    class Meta:
        ordering = ['salary']
        db_table = 'vacancies'


class Partner(Base):
    name = models.CharField(max_length=100, unique=True)
    logo = models.ImageField(upload_to='static/partners/')
    website = models.URLField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'partners'
        ordering = ['name']

IGI/LR5/zoo_shop/zoo_shop_app/forms.py
import django.forms
from django.contrib.auth import forms
from zoo_shop_app.models import *
from zoo_shop_app.models import Review
from django.core.exceptions import ValidationError
import re


class UserRegistrationForm(forms.UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        birth_date = models.DateField(
            validators=[MaxValueValidator(datetime.date.today() - datetime.timedelta(days=18 * 365),
                                          message="Вы должны быть старше 18 лет для регистрации!!!")], null=True)
        user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
        name = models.CharField(max_length=30, unique=True)
        email = models.EmailField(max_length=50, unique=True)
        phone = models.CharField(max_length=13, unique=True)
        password = models.CharField(max_length=50)


def validate_phone_number(value):
    phone_pattern = re.compile(r'^\+37529\d{7}$')
    if not phone_pattern.match(value):
        raise ValidationError('Неверный формат номера телефона. Номер должен начинаться с "+37529" и иметь 13 символов.')


class ProfileRegistrationForm(django.forms.ModelForm):
    phone = django.forms.CharField(validators=[validate_phone_number])

    class Meta:
        model = Client
        fields = ('name', 'email', 'birth_date', 'phone', 'photo')
        widgets = {
            'birth_date': django.forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'photo': django.forms.FileInput(attrs={'class': 'form-control', 'required': False})
        }


class LoginForm(django.forms.Form):
    username = django.forms.CharField()
    password = django.forms.CharField(widget=django.forms.PasswordInput)


class ProfileForm(django.forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'birth_date', 'phone', 'photo')
        widgets = {'birth_date': django.forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
                   'photo': django.forms.FileInput(attrs={'class': 'form-control', 'required': False})
                   }


class ReviewForm(django.forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rate']


class VacancyForm(django.forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = ['position', 'description', 'salary']


class PromocodeForm(django.forms.ModelForm):
    class Meta:
        model = Promocode
        fields = ['discount', 'archived', 'code', 'text', 'valid_date']
        widgets = {
            'valid_date': django.forms.DateInput(attrs={'type': 'date'}),
        }


class AddToCartForm(django.forms.Form):
    quantity = django.forms.IntegerField(min_value=1, max_value=100, initial=1)


class AddressForm(django.forms.Form):
    address = django.forms.CharField(max_length=100, required=True)


class PromoCodeForm(django.forms.Form):
    promo_code = django.forms.CharField(max_length=10, required=False)

    def clean_promo_code(self):
        promo_code = self.cleaned_data.get('promo_code')

        if promo_code:
            if not Promocode.objects.filter(code=promo_code, archived=False).exists():
                raise django.forms.ValidationError("Промокод недействителен или не существует.")
        return promo_code


class FAQForm(django.forms.ModelForm):
    class Meta:
        model = FAQ
        fields = ['question', 'answer']

IGI/LR5/zoo_shop/zoo_shop_app/templates/shopping_cart/add_to_cart.html
{% extends 'base.html' %}

{% block content %}
<h1>Добавить товар в корзину</h1>
<form method="post" action="{% url 'add_to_cart' product.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить в корзину</button>
</form>
{% endblock %}

IGI/LR5/zoo_shop/zoo_shop_app/templates/shopping_cart/cart_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Shopping Cart</h1>
  <ul>
    {% for item in cart_summary %}
      <li>{{ item.product.name }}: {{ item.quantity }} x {{ item.product.price }} = {{ item.total_cost }}</li>
    {% endfor %}
  </ul>
  <p>Total Cost: {{ total_cost }}</p>

  <p><form action="{% url 'create_order' %}" method="get">
    <button type="submit" class="btn btn-primary">Перейти к оформлению заказа</button>
    </form></p>
    <p>
    <form action="{% url 'clear_cart' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-secondary">Очистить корзину</button>
    </form> </p>
    <p>
  <form action="{% url 'products' %}" method="get">
    <button type="submit" class="btn btn-primary">Продолжить покупки</button>
  </form> </p>

{% endblock %}

IGI/LR5/zoo_shop/zoo_shop_app/templates/shopping_cart/cart_management.html
{% extends 'base.html' %}

{% block content %}
<h1>Корзина</h1>

<ul>
    {% for item in cart_summary %}
        <li>
            {{ item.product.name }}:
            <strong>{{ item.quantity }}</strong> x {{ item.product.price }} = {{ item.total_cost }}

            <form action="{% url 'remove_from_cart' item.id %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit">Удалить из корзины</button>
            </form>

            <form action="{% url 'update_cart' item.id %}" method="post" style="display:inline;">
                {% csrf_token %}
                <input type="number" name="quantity" value="{{ item.quantity }}" min="1" max="100">
                <button type="submit">Изменить количество</button>
            </form>
        </li>
    {% empty %}
        <li>Корзина пуста.</li>
    {% endfor %}
</ul>

<p>Общая стоимость: {{ total_cost }}</p>

<p>
    <form action="{% url 'create_order' %}" method="get">
        <button type="submit">Перейти к оформлению заказа</button>
    </form>
</p>

<form action="{% url 'clear_cart' %}" method="post">
    {% csrf_token %}
    <button type="submit">Очистить корзину</button>
</form>

<p>
    <form action="{% url 'products' %}" method="get">
        <button type="submit">Продолжить покупки</button>
    </form>
</p>

{% endblock %}

IGI/LR5/zoo_shop/zoo_shop_app/templates/shopping_cart/enter_address.html
{% extends "base.html" %}

{% block content %}
    <h1>Оформление заказа</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        <div>
            <label for="id_address">Адрес:</label>
            {{ address_form.address }}
            {% if address_form.address.errors %}
                <div class="error">{{ address_form.address.errors }}</div>
            {% endif %}
        </div>
        <br>
        <div>
            <label for="id_promo_code">Введите промокод (необязательно):</label>
            {{ promo_code_form.promo_code }}
            {% if promo_code_form.promo_code.errors %}
                <div class="error">{{ promo_code_form.promo_code.errors }}</div>
            {% endif %}
        </div>

        <button type="submit">Оформить заказ</button>
    </form>

    <p>
        <form action="{% url 'cart_management' %}" method="get">
            <button type="submit">Вернуться к корзине</button>
        </form>
    </p>
{% endblock %}

IGI/LR5/zoo_shop/zoo_shop_app/templates/shopping_cart/order_confirmation.html
{% extends "base.html" %}

{% block content %}
  <h1>Order Confirmation</h1>
  <p>Thank you for your purchase! Your order ID is {{ order.id }}.</p>
  <p>Total Cost: {{ order.total_cost }}</p>
  <p>Delivery Address: {{ order.address }}</p>
    <p>
  <form action="{% url 'products' %}" method="get">
    <button type="submit" class="btn btn-primary">Продолжить покупки</button>
  </form> </p>
{% endblock %}